"""add_resource_blacklist_table

Revision ID: 1fd617418fe7
Revises: d76f2dd16f26
Create Date: 2025-10-27 16:13:11.643027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd617418fe7'
down_revision: Union[str, None] = 'd76f2dd16f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create resource_blacklist table
    op.create_table(
        'resource_blacklist',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('type', sa.String(length=20), nullable=True),
        sa.Column('subject_name', sa.String(length=50), nullable=True),
        sa.Column('topic', sa.String(length=255), nullable=True),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('blacklisted_by', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_blacklist_url'), 'resource_blacklist', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop resource_blacklist table
    op.drop_index(op.f('ix_resource_blacklist_url'), table_name='resource_blacklist')
    op.drop_table('resource_blacklist')
    # ### end Alembic commands ###
