"""add_resource_tables

Revision ID: 280a6c5218b3
Revises: 9bad78e712dc
Create Date: 2025-10-27 15:25:36.868300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280a6c5218b3'
down_revision: Union[str, None] = '9bad78e712dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create resources table
    op.create_table('resources',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('subject_name', sa.String(length=50), nullable=True),
        sa.Column('topic', sa.String(length=255), nullable=True),
        sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
        sa.Column('extra_data', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Create recommendation_resources junction table
    op.create_table('recommendation_resources',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('recommendation_id', sa.String(length=36), nullable=False),
        sa.Column('resource_id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
        sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_resources_recommendation_id'), 'recommendation_resources', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_resources_resource_id'), 'recommendation_resources', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_resources_resource_id'), table_name='recommendation_resources')
    op.drop_index(op.f('ix_recommendation_resources_recommendation_id'), table_name='recommendation_resources')
    op.drop_table('recommendation_resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
