"""Initial database schema

Revision ID: a326f199cf9d
Revises: 
Create Date: 2025-10-26 14:10:27.768552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a326f199cf9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('class_section', sa.String(length=10), nullable=True),
    sa.Column('program', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('exam_name', sa.String(length=255), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('booklet_type', sa.String(length=10), nullable=True),
    sa.Column('exam_number', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_exam_date'), 'exams', ['exam_date'], unique=False)
    op.create_index(op.f('ix_exams_student_id'), 'exams', ['student_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('issue_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('impact_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_student_id'), 'recommendations', ['student_id'], unique=False)
    op.create_table('exam_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('total_correct', sa.Integer(), nullable=False),
    sa.Column('total_wrong', sa.Integer(), nullable=False),
    sa.Column('total_blank', sa.Integer(), nullable=False),
    sa.Column('net_score', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('net_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('class_rank', sa.Integer(), nullable=True),
    sa.Column('class_total', sa.Integer(), nullable=True),
    sa.Column('school_rank', sa.Integer(), nullable=True),
    sa.Column('school_total', sa.Integer(), nullable=True),
    sa.Column('class_avg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('school_avg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_results_exam_id'), 'exam_results', ['exam_id'], unique=True)
    op.create_table('learning_outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('subject_name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('outcome_description', sa.Text(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('acquired', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('student_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('class_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('school_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_outcomes_exam_id'), 'learning_outcomes', ['exam_id'], unique=False)
    op.create_index(op.f('ix_learning_outcomes_subject_name'), 'learning_outcomes', ['subject_name'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('subject_name', sa.String(length=50), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=True),
    sa.Column('student_answer', sa.String(length=1), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('is_blank', sa.Boolean(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_exam_id'), 'questions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_questions_subject_name'), 'questions', ['subject_name'], unique=False)
    op.create_table('subject_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('subject_name', sa.String(length=50), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Integer(), nullable=False),
    sa.Column('blank', sa.Integer(), nullable=False),
    sa.Column('net_score', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('net_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('class_rank', sa.Integer(), nullable=True),
    sa.Column('class_avg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('school_rank', sa.Integer(), nullable=True),
    sa.Column('school_avg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_results_exam_id'), 'subject_results', ['exam_id'], unique=False)
    op.create_index(op.f('ix_subject_results_subject_name'), 'subject_results', ['subject_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_results_subject_name'), table_name='subject_results')
    op.drop_index(op.f('ix_subject_results_exam_id'), table_name='subject_results')
    op.drop_table('subject_results')
    op.drop_index(op.f('ix_questions_subject_name'), table_name='questions')
    op.drop_index(op.f('ix_questions_exam_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_learning_outcomes_subject_name'), table_name='learning_outcomes')
    op.drop_index(op.f('ix_learning_outcomes_exam_id'), table_name='learning_outcomes')
    op.drop_table('learning_outcomes')
    op.drop_index(op.f('ix_exam_results_exam_id'), table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index(op.f('ix_recommendations_student_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_exams_student_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_exam_date'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
