"""add_resource_quality_fields

Revision ID: d76f2dd16f26
Revises: 280a6c5218b3
Create Date: 2025-10-27 15:58:11.511293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd76f2dd16f26'
down_revision: Union[str, None] = '280a6c5218b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new resource quality fields
    op.add_column('resources', sa.Column('learning_outcome_ids', sa.JSON(), nullable=True))
    op.add_column('resources', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('resources', sa.Column('education_level', sa.String(length=20), nullable=True))
    op.add_column('resources', sa.Column('curator_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove resource quality fields
    op.drop_column('resources', 'curator_notes')
    op.drop_column('resources', 'education_level')
    op.drop_column('resources', 'quality_score')
    op.drop_column('resources', 'learning_outcome_ids')
    # ### end Alembic commands ###
