"""Add exam status and validation data fields

Revision ID: e8f11ffa49d1
Revises: a326f199cf9d
Create Date: 2025-10-26 16:39:06.237764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f11ffa49d1'
down_revision: Union[str, None] = 'a326f199cf9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to add status with a default value to handle existing rows
    op.add_column('exams', sa.Column('status', sa.String(length=25), nullable=False, server_default='confirmed'))
    op.add_column('exams', sa.Column('claude_data', sa.Text(), nullable=True))
    op.add_column('exams', sa.Column('local_data', sa.Text(), nullable=True))
    op.add_column('exams', sa.Column('validation_report', sa.Text(), nullable=True))
    op.add_column('exams', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'confirmed_at')
    op.drop_column('exams', 'validation_report')
    op.drop_column('exams', 'local_data')
    op.drop_column('exams', 'claude_data')
    op.drop_column('exams', 'status')
    # ### end Alembic commands ###
